# Generated by Django 2.2 on 2019-04-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailgun_email', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookclubmailinglist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
