# Generated by Django 2.2 on 2019-04-11 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailgun_email', '0002_auto_20190410_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookclubmailinglist',
            options={'verbose_name_plural': 'Email'},
        ),
    ]
