# Generated by Django 2.2 on 2019-04-09 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='owner',
        ),
    ]
