# Generated by Django 2.2 on 2019-04-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
